### ISSUE TITLE
cannot write files when Title contains /

### ISSUE THREAD

**Issue by artmg** [jeffkowalski/geeknote#17]
_note.title_ is used as the filename for **gnsync** download and twoway. When the note.title contains illegal filename characters such as / slash it fails to write the file. Previously it failed with the log error "[Errno 2] No such file or directory" but now it just fails silently.

I believe the issue could be fixed in **_create_file** 

        path = os.path.join(self.path, note.title + self.extension)

but my python coding skills fall short of making sure the other dependent code does not get borked:

* the tests **if** _xxxxx_ **== n.title** in both sync directions
* where **_update_note** sets **title=**

**Comment by jeffkowalski** [comment]
#55 fixes the problem of filenames on save.  
The path separator character within the filename is replaced by '-'.  
(Of course if that local note is then modified, the upward sync will create a new note with that modified name. This seems like a reasonable compromise, since there's generally no good way to keep the modified filename associated with the original title.)
