### ISSUE TITLE
Unable to edit note using atom.io editor

### ISSUE THREAD

**Issue by combatdud3** [jeffkowalski/geeknote#25]
I understand this may be beyond the role of a console client...

When using atom.io as the default editor geeknote will open the editor and the file will show. However it also saves the note immediately and any changes made aren't reflected.

I think it may be because atom detached from the shell. My programming skills are quite limited. But based on:

```python

    def _editWithEditorInThread(self, inputData, note=None, raw=None):
        editor_userprop = getEditor(self.getStorage())
        noteExt_userprop = getNoteExt(self.getStorage()).split(',')[bool(raw)]
        if note:
            self.getEvernote().loadNoteContent(note)
            editor = Editor(editor_userprop, note.content, noteExt_userprop, raw)
        else:
            editor = Editor(editor_userprop, '', noteExt_userprop, raw)
        thread = EditorThread(editor)
        thread.start()

        result = True
        prevChecksum = editor.getTempfileChecksum()
```
It looks like geeknote is relying on the editor to keep hold of the shell to prevent it from progressing until the thread is closed. I think.

If you need anything else from me, please let me know.

**Comment by jeffkowalski** [comment]
You're correct, geeknote only waits long enough for the editor process to complete.  This is by design.
The atom script you're running actually spawns a new process, then exits.
There is an option to tell the atom script to wait on its subprocess, which will solve the problem.
Use something like
```geeknote settings --editor "/usr/bin/atom -w"```
Note the ```-w``` is the flag that tells atom to wait for its spawned process to complete before exiting.
