### ISSUE TITLE
can not upgrade

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#48]
$ pip install --upgrade .
Processing /home/vitaly/geeknote
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-6o4htz1g-build/setup.py", line 48
        print "installing autocomplete"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by jeffkowalski** [comment]
which version of pip are you using?
```pip --version```

which version of python are you using?
```python --version```

**Comment by vitaly-zdanevich** [comment]
pip: 8.1.2
Python: 2.7.6

**Comment by jeffkowalski** [comment]
Thanks for the version info, Vitaly.
I'm having trouble reproducing the error here.  
What happens if you add parens around the arguments in the print statement in setup.py, line 48, as in
```print("installing autocomplete")```

**Comment by vitaly-zdanevich** [comment]
$ pip install --upgrade .
Processing /home/vitaly/geeknote
Collecting evernote>=1.25 (from geeknote==2.0.3)
  Using cached evernote-1.25.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mo406itv/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'

**Comment by jeffkowalski** [comment]
Thanks for trying to add parens to the ```print``` statement, Vitaly.

I see it's now failing on the call to ```exec```,  in a library (evernote) that's known to work and not even ours in this repo.

I therefore suspect you're actually running python3 somehow.  This theory is consistent with the changes that were made in python from version 2 to version 3.  For example, you may refer to the "fixers" for [print](https://docs.python.org/2/library/2to3.html#2to3fixer-print) and [exec](https://docs.python.org/2/library/2to3.html#2to3fixer-exec), which point to the errors you're seeing.

Note that python3 is not supported by geeknote, largely because the evernote library isn't available there.  So, I'd suggest trying to figure out why you have a python3 running.

What is the output from ```whereis python``` and ```which python``` ?   That may lead you in the right direction.

**Comment by vitaly-zdanevich** [comment]
Yes thank you - I fixes this with
`pip2 install --upgrade .`

**Comment by jeffkowalski** [comment]
Glad it worked out for you.  I'll add a note in the readme.
