### ISSUE TITLE
unused dependency on proxyenv

### ISSUE THREAD

**Issue by pva** [jeffkowalski/geeknote#82]
Please, drop proxyenv from setup.py. It is not used, still is required as dependency:

peter@i7 /media/oss/geeknote $ grep -r proxyenv .
./tests/test_sandbox.py:#from proxyenv.proxyenv import ProxyFactory
./requirements.txt:proxyenv
./geeknote.rb:  # for proxyenv
./geeknote.rb:  resource "proxyenv" do
./geeknote.rb:    url "https://files.pythonhosted.org/packages/69/98/46baccf9ce353828726e0d302dad201e634fe4b50f6f61891f0721f40789/proxyenv-0.5.1.tar.gz"

TIA

**Comment by jeffkowalski** [comment]
It's still used by ```class TestSandboxWithProxy```, although that won't be tested unless ```config.DEV_MODE``` is True.  I can remove some confusion by only importing from proxyenv when that flag is set, rather than commenting out that line.
Btw, is there a problem with installing proxyenv?  I'm curious why you found the dependency to be problematic.
