### ISSUE TITLE
how to set editor to Atom, MacDown, Macvim or other OS X graphical editor?

### ISSUE THREAD

**Issue by foice** [jeffkowalski/geeknote#83]
Hi, I have tried `geeknote settings --editor 'macvim -f'` but it does not work at all while `geeknote settings --editor 'mopen'`  where mopen is one-line script `open -a MacDown.app "$1"` opens a window with a tempfile, but is not able to save it into a note then. 

Is it possible to use this type of editors? any suggestion?

**Comment by jeffkowalski** [comment]
I'm sorry I don't have an OSX machine to test this on, but under Linux Mint, the analogous ```geeknote settings --editor "vim -f"```
seems to work fine.  If you set DEBUG=TRUE in config.py, you can see what's going to be used for the editor call, as in 
```editor.py edit 354 : launch system editor: vim -f /tmp/tmpytu3Ra.markdown```.
You've probably figured out that the editor command must remain in the foreground.  Geeknote waits for the editor command to complete, then reads the contents of the temporary file.  If the command returns early due to forking to the background, or passing to a different process, then the file contents won't change.
